#!/bin/bash

ARGS=''
for i in "$@"; do 
    ARGS="$ARGS \"${i//\"/\\\"}\""
done;

CMD="grep -Hnr --color=always --exclude-dir=build --include=*.{cc,c,cpp,cu,h,hpp,ipp,py,lua,inl,ui} -E $ARGS"
#echo $CMD

exec bash -c "$CMD"
